package com.unbank.mybatis.mapper;

import com.unbank.mybatis.entity.PersistentLogin;
import com.unbank.mybatis.entity.PersistentLoginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersistentLoginMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table persistent_logins
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	int countByExample(PersistentLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table persistent_logins
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	int deleteByExample(PersistentLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table persistent_logins
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	int deleteByPrimaryKey(String series);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table persistent_logins
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	int insert(PersistentLogin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table persistent_logins
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	int insertSelective(PersistentLogin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table persistent_logins
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	List<PersistentLogin> selectByExample(PersistentLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table persistent_logins
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	PersistentLogin selectByPrimaryKey(String series);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table persistent_logins
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	int updateByExampleSelective(@Param("record") PersistentLogin record,
			@Param("example") PersistentLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table persistent_logins
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	int updateByExample(@Param("record") PersistentLogin record, @Param("example") PersistentLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table persistent_logins
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	int updateByPrimaryKeySelective(PersistentLogin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table persistent_logins
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	int updateByPrimaryKey(PersistentLogin record);
}