package com.unbank.mybatis.mapper;

import com.unbank.mybatis.entity.UserSite;
import com.unbank.mybatis.entity.UserSiteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserSiteMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_site
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	int countByExample(UserSiteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_site
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	int deleteByExample(UserSiteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_site
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_site
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	int insert(UserSite record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_site
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	int insertSelective(UserSite record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_site
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	List<UserSite> selectByExample(UserSiteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_site
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	UserSite selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_site
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	int updateByExampleSelective(@Param("record") UserSite record, @Param("example") UserSiteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_site
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	int updateByExample(@Param("record") UserSite record, @Param("example") UserSiteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_site
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	int updateByPrimaryKeySelective(UserSite record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_site
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	int updateByPrimaryKey(UserSite record);
}