package com.unbank.mybatis.entity;

public class Parser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column parser.id
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column parser.site_id
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private Integer siteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column parser.host
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private String host;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column parser.parse_rule
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private String parseRule;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column parser.id
	 * @return  the value of parser.id
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column parser.id
	 * @param id  the value for parser.id
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column parser.site_id
	 * @return  the value of parser.site_id
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public Integer getSiteId() {
		return siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column parser.site_id
	 * @param siteId  the value for parser.site_id
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setSiteId(Integer siteId) {
		this.siteId = siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column parser.host
	 * @return  the value of parser.host
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public String getHost() {
		return host;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column parser.host
	 * @param host  the value for parser.host
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setHost(String host) {
		this.host = host;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column parser.parse_rule
	 * @return  the value of parser.parse_rule
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public String getParseRule() {
		return parseRule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column parser.parse_rule
	 * @param parseRule  the value for parser.parse_rule
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setParseRule(String parseRule) {
		this.parseRule = parseRule;
	}
}