package com.unbank.mybatis.entity;

import java.util.Date;

public class Site {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site.id
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site.site_name
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private String siteName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site.section_name
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private String sectionName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site.url
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site.status
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site.view_num
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private Integer viewNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site.c_id
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private Integer cId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site.c_date
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private Date cDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site.rank
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private Integer rank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site.order_num
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private Integer orderNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site.price
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private Double price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site.last_update
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private Date lastUpdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site.retry_time
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private Integer retryTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site.sleep_time
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private Integer sleepTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site.time_out
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private Integer timeOut;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site.id
	 * @return  the value of site.id
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site.id
	 * @param id  the value for site.id
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site.site_name
	 * @return  the value of site.site_name
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public String getSiteName() {
		return siteName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site.site_name
	 * @param siteName  the value for site.site_name
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setSiteName(String siteName) {
		this.siteName = siteName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site.section_name
	 * @return  the value of site.section_name
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public String getSectionName() {
		return sectionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site.section_name
	 * @param sectionName  the value for site.section_name
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setSectionName(String sectionName) {
		this.sectionName = sectionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site.url
	 * @return  the value of site.url
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site.url
	 * @param url  the value for site.url
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site.status
	 * @return  the value of site.status
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site.status
	 * @param status  the value for site.status
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site.view_num
	 * @return  the value of site.view_num
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public Integer getViewNum() {
		return viewNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site.view_num
	 * @param viewNum  the value for site.view_num
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setViewNum(Integer viewNum) {
		this.viewNum = viewNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site.c_id
	 * @return  the value of site.c_id
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public Integer getcId() {
		return cId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site.c_id
	 * @param cId  the value for site.c_id
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setcId(Integer cId) {
		this.cId = cId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site.c_date
	 * @return  the value of site.c_date
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public Date getcDate() {
		return cDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site.c_date
	 * @param cDate  the value for site.c_date
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setcDate(Date cDate) {
		this.cDate = cDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site.rank
	 * @return  the value of site.rank
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public Integer getRank() {
		return rank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site.rank
	 * @param rank  the value for site.rank
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setRank(Integer rank) {
		this.rank = rank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site.order_num
	 * @return  the value of site.order_num
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public Integer getOrderNum() {
		return orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site.order_num
	 * @param orderNum  the value for site.order_num
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site.price
	 * @return  the value of site.price
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site.price
	 * @param price  the value for site.price
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site.last_update
	 * @return  the value of site.last_update
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public Date getLastUpdate() {
		return lastUpdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site.last_update
	 * @param lastUpdate  the value for site.last_update
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site.retry_time
	 * @return  the value of site.retry_time
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public Integer getRetryTime() {
		return retryTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site.retry_time
	 * @param retryTime  the value for site.retry_time
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setRetryTime(Integer retryTime) {
		this.retryTime = retryTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site.sleep_time
	 * @return  the value of site.sleep_time
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public Integer getSleepTime() {
		return sleepTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site.sleep_time
	 * @param sleepTime  the value for site.sleep_time
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setSleepTime(Integer sleepTime) {
		this.sleepTime = sleepTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site.time_out
	 * @return  the value of site.time_out
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public Integer getTimeOut() {
		return timeOut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site.time_out
	 * @param timeOut  the value for site.time_out
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setTimeOut(Integer timeOut) {
		this.timeOut = timeOut;
	}
}