package com.unbank.mybatis.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SiteExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table site
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table site
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table site
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public SiteExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table site
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andSiteNameIsNull() {
			addCriterion("site_name is null");
			return (Criteria) this;
		}

		public Criteria andSiteNameIsNotNull() {
			addCriterion("site_name is not null");
			return (Criteria) this;
		}

		public Criteria andSiteNameEqualTo(String value) {
			addCriterion("site_name =", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameNotEqualTo(String value) {
			addCriterion("site_name <>", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameGreaterThan(String value) {
			addCriterion("site_name >", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameGreaterThanOrEqualTo(String value) {
			addCriterion("site_name >=", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameLessThan(String value) {
			addCriterion("site_name <", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameLessThanOrEqualTo(String value) {
			addCriterion("site_name <=", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameLike(String value) {
			addCriterion("site_name like", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameNotLike(String value) {
			addCriterion("site_name not like", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameIn(List<String> values) {
			addCriterion("site_name in", values, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameNotIn(List<String> values) {
			addCriterion("site_name not in", values, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameBetween(String value1, String value2) {
			addCriterion("site_name between", value1, value2, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameNotBetween(String value1, String value2) {
			addCriterion("site_name not between", value1, value2, "siteName");
			return (Criteria) this;
		}

		public Criteria andSectionNameIsNull() {
			addCriterion("section_name is null");
			return (Criteria) this;
		}

		public Criteria andSectionNameIsNotNull() {
			addCriterion("section_name is not null");
			return (Criteria) this;
		}

		public Criteria andSectionNameEqualTo(String value) {
			addCriterion("section_name =", value, "sectionName");
			return (Criteria) this;
		}

		public Criteria andSectionNameNotEqualTo(String value) {
			addCriterion("section_name <>", value, "sectionName");
			return (Criteria) this;
		}

		public Criteria andSectionNameGreaterThan(String value) {
			addCriterion("section_name >", value, "sectionName");
			return (Criteria) this;
		}

		public Criteria andSectionNameGreaterThanOrEqualTo(String value) {
			addCriterion("section_name >=", value, "sectionName");
			return (Criteria) this;
		}

		public Criteria andSectionNameLessThan(String value) {
			addCriterion("section_name <", value, "sectionName");
			return (Criteria) this;
		}

		public Criteria andSectionNameLessThanOrEqualTo(String value) {
			addCriterion("section_name <=", value, "sectionName");
			return (Criteria) this;
		}

		public Criteria andSectionNameLike(String value) {
			addCriterion("section_name like", value, "sectionName");
			return (Criteria) this;
		}

		public Criteria andSectionNameNotLike(String value) {
			addCriterion("section_name not like", value, "sectionName");
			return (Criteria) this;
		}

		public Criteria andSectionNameIn(List<String> values) {
			addCriterion("section_name in", values, "sectionName");
			return (Criteria) this;
		}

		public Criteria andSectionNameNotIn(List<String> values) {
			addCriterion("section_name not in", values, "sectionName");
			return (Criteria) this;
		}

		public Criteria andSectionNameBetween(String value1, String value2) {
			addCriterion("section_name between", value1, value2, "sectionName");
			return (Criteria) this;
		}

		public Criteria andSectionNameNotBetween(String value1, String value2) {
			addCriterion("section_name not between", value1, value2, "sectionName");
			return (Criteria) this;
		}

		public Criteria andUrlIsNull() {
			addCriterion("url is null");
			return (Criteria) this;
		}

		public Criteria andUrlIsNotNull() {
			addCriterion("url is not null");
			return (Criteria) this;
		}

		public Criteria andUrlEqualTo(String value) {
			addCriterion("url =", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotEqualTo(String value) {
			addCriterion("url <>", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlGreaterThan(String value) {
			addCriterion("url >", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlGreaterThanOrEqualTo(String value) {
			addCriterion("url >=", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLessThan(String value) {
			addCriterion("url <", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLessThanOrEqualTo(String value) {
			addCriterion("url <=", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLike(String value) {
			addCriterion("url like", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotLike(String value) {
			addCriterion("url not like", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlIn(List<String> values) {
			addCriterion("url in", values, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotIn(List<String> values) {
			addCriterion("url not in", values, "url");
			return (Criteria) this;
		}

		public Criteria andUrlBetween(String value1, String value2) {
			addCriterion("url between", value1, value2, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotBetween(String value1, String value2) {
			addCriterion("url not between", value1, value2, "url");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andViewNumIsNull() {
			addCriterion("view_num is null");
			return (Criteria) this;
		}

		public Criteria andViewNumIsNotNull() {
			addCriterion("view_num is not null");
			return (Criteria) this;
		}

		public Criteria andViewNumEqualTo(Integer value) {
			addCriterion("view_num =", value, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumNotEqualTo(Integer value) {
			addCriterion("view_num <>", value, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumGreaterThan(Integer value) {
			addCriterion("view_num >", value, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("view_num >=", value, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumLessThan(Integer value) {
			addCriterion("view_num <", value, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumLessThanOrEqualTo(Integer value) {
			addCriterion("view_num <=", value, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumIn(List<Integer> values) {
			addCriterion("view_num in", values, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumNotIn(List<Integer> values) {
			addCriterion("view_num not in", values, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumBetween(Integer value1, Integer value2) {
			addCriterion("view_num between", value1, value2, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumNotBetween(Integer value1, Integer value2) {
			addCriterion("view_num not between", value1, value2, "viewNum");
			return (Criteria) this;
		}

		public Criteria andCIdIsNull() {
			addCriterion("c_id is null");
			return (Criteria) this;
		}

		public Criteria andCIdIsNotNull() {
			addCriterion("c_id is not null");
			return (Criteria) this;
		}

		public Criteria andCIdEqualTo(Integer value) {
			addCriterion("c_id =", value, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdNotEqualTo(Integer value) {
			addCriterion("c_id <>", value, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdGreaterThan(Integer value) {
			addCriterion("c_id >", value, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("c_id >=", value, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdLessThan(Integer value) {
			addCriterion("c_id <", value, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdLessThanOrEqualTo(Integer value) {
			addCriterion("c_id <=", value, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdIn(List<Integer> values) {
			addCriterion("c_id in", values, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdNotIn(List<Integer> values) {
			addCriterion("c_id not in", values, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdBetween(Integer value1, Integer value2) {
			addCriterion("c_id between", value1, value2, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdNotBetween(Integer value1, Integer value2) {
			addCriterion("c_id not between", value1, value2, "cId");
			return (Criteria) this;
		}

		public Criteria andCDateIsNull() {
			addCriterion("c_date is null");
			return (Criteria) this;
		}

		public Criteria andCDateIsNotNull() {
			addCriterion("c_date is not null");
			return (Criteria) this;
		}

		public Criteria andCDateEqualTo(Date value) {
			addCriterion("c_date =", value, "cDate");
			return (Criteria) this;
		}

		public Criteria andCDateNotEqualTo(Date value) {
			addCriterion("c_date <>", value, "cDate");
			return (Criteria) this;
		}

		public Criteria andCDateGreaterThan(Date value) {
			addCriterion("c_date >", value, "cDate");
			return (Criteria) this;
		}

		public Criteria andCDateGreaterThanOrEqualTo(Date value) {
			addCriterion("c_date >=", value, "cDate");
			return (Criteria) this;
		}

		public Criteria andCDateLessThan(Date value) {
			addCriterion("c_date <", value, "cDate");
			return (Criteria) this;
		}

		public Criteria andCDateLessThanOrEqualTo(Date value) {
			addCriterion("c_date <=", value, "cDate");
			return (Criteria) this;
		}

		public Criteria andCDateIn(List<Date> values) {
			addCriterion("c_date in", values, "cDate");
			return (Criteria) this;
		}

		public Criteria andCDateNotIn(List<Date> values) {
			addCriterion("c_date not in", values, "cDate");
			return (Criteria) this;
		}

		public Criteria andCDateBetween(Date value1, Date value2) {
			addCriterion("c_date between", value1, value2, "cDate");
			return (Criteria) this;
		}

		public Criteria andCDateNotBetween(Date value1, Date value2) {
			addCriterion("c_date not between", value1, value2, "cDate");
			return (Criteria) this;
		}

		public Criteria andRankIsNull() {
			addCriterion("rank is null");
			return (Criteria) this;
		}

		public Criteria andRankIsNotNull() {
			addCriterion("rank is not null");
			return (Criteria) this;
		}

		public Criteria andRankEqualTo(Integer value) {
			addCriterion("rank =", value, "rank");
			return (Criteria) this;
		}

		public Criteria andRankNotEqualTo(Integer value) {
			addCriterion("rank <>", value, "rank");
			return (Criteria) this;
		}

		public Criteria andRankGreaterThan(Integer value) {
			addCriterion("rank >", value, "rank");
			return (Criteria) this;
		}

		public Criteria andRankGreaterThanOrEqualTo(Integer value) {
			addCriterion("rank >=", value, "rank");
			return (Criteria) this;
		}

		public Criteria andRankLessThan(Integer value) {
			addCriterion("rank <", value, "rank");
			return (Criteria) this;
		}

		public Criteria andRankLessThanOrEqualTo(Integer value) {
			addCriterion("rank <=", value, "rank");
			return (Criteria) this;
		}

		public Criteria andRankIn(List<Integer> values) {
			addCriterion("rank in", values, "rank");
			return (Criteria) this;
		}

		public Criteria andRankNotIn(List<Integer> values) {
			addCriterion("rank not in", values, "rank");
			return (Criteria) this;
		}

		public Criteria andRankBetween(Integer value1, Integer value2) {
			addCriterion("rank between", value1, value2, "rank");
			return (Criteria) this;
		}

		public Criteria andRankNotBetween(Integer value1, Integer value2) {
			addCriterion("rank not between", value1, value2, "rank");
			return (Criteria) this;
		}

		public Criteria andOrderNumIsNull() {
			addCriterion("order_num is null");
			return (Criteria) this;
		}

		public Criteria andOrderNumIsNotNull() {
			addCriterion("order_num is not null");
			return (Criteria) this;
		}

		public Criteria andOrderNumEqualTo(Integer value) {
			addCriterion("order_num =", value, "orderNum");
			return (Criteria) this;
		}

		public Criteria andOrderNumNotEqualTo(Integer value) {
			addCriterion("order_num <>", value, "orderNum");
			return (Criteria) this;
		}

		public Criteria andOrderNumGreaterThan(Integer value) {
			addCriterion("order_num >", value, "orderNum");
			return (Criteria) this;
		}

		public Criteria andOrderNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("order_num >=", value, "orderNum");
			return (Criteria) this;
		}

		public Criteria andOrderNumLessThan(Integer value) {
			addCriterion("order_num <", value, "orderNum");
			return (Criteria) this;
		}

		public Criteria andOrderNumLessThanOrEqualTo(Integer value) {
			addCriterion("order_num <=", value, "orderNum");
			return (Criteria) this;
		}

		public Criteria andOrderNumIn(List<Integer> values) {
			addCriterion("order_num in", values, "orderNum");
			return (Criteria) this;
		}

		public Criteria andOrderNumNotIn(List<Integer> values) {
			addCriterion("order_num not in", values, "orderNum");
			return (Criteria) this;
		}

		public Criteria andOrderNumBetween(Integer value1, Integer value2) {
			addCriterion("order_num between", value1, value2, "orderNum");
			return (Criteria) this;
		}

		public Criteria andOrderNumNotBetween(Integer value1, Integer value2) {
			addCriterion("order_num not between", value1, value2, "orderNum");
			return (Criteria) this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("price is null");
			return (Criteria) this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("price is not null");
			return (Criteria) this;
		}

		public Criteria andPriceEqualTo(Double value) {
			addCriterion("price =", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotEqualTo(Double value) {
			addCriterion("price <>", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThan(Double value) {
			addCriterion("price >", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(Double value) {
			addCriterion("price >=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThan(Double value) {
			addCriterion("price <", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThanOrEqualTo(Double value) {
			addCriterion("price <=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceIn(List<Double> values) {
			addCriterion("price in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotIn(List<Double> values) {
			addCriterion("price not in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceBetween(Double value1, Double value2) {
			addCriterion("price between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotBetween(Double value1, Double value2) {
			addCriterion("price not between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andLastUpdateIsNull() {
			addCriterion("last_update is null");
			return (Criteria) this;
		}

		public Criteria andLastUpdateIsNotNull() {
			addCriterion("last_update is not null");
			return (Criteria) this;
		}

		public Criteria andLastUpdateEqualTo(Date value) {
			addCriterion("last_update =", value, "lastUpdate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateNotEqualTo(Date value) {
			addCriterion("last_update <>", value, "lastUpdate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateGreaterThan(Date value) {
			addCriterion("last_update >", value, "lastUpdate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateGreaterThanOrEqualTo(Date value) {
			addCriterion("last_update >=", value, "lastUpdate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateLessThan(Date value) {
			addCriterion("last_update <", value, "lastUpdate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateLessThanOrEqualTo(Date value) {
			addCriterion("last_update <=", value, "lastUpdate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateIn(List<Date> values) {
			addCriterion("last_update in", values, "lastUpdate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateNotIn(List<Date> values) {
			addCriterion("last_update not in", values, "lastUpdate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateBetween(Date value1, Date value2) {
			addCriterion("last_update between", value1, value2, "lastUpdate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateNotBetween(Date value1, Date value2) {
			addCriterion("last_update not between", value1, value2, "lastUpdate");
			return (Criteria) this;
		}

		public Criteria andRetryTimeIsNull() {
			addCriterion("retry_time is null");
			return (Criteria) this;
		}

		public Criteria andRetryTimeIsNotNull() {
			addCriterion("retry_time is not null");
			return (Criteria) this;
		}

		public Criteria andRetryTimeEqualTo(Integer value) {
			addCriterion("retry_time =", value, "retryTime");
			return (Criteria) this;
		}

		public Criteria andRetryTimeNotEqualTo(Integer value) {
			addCriterion("retry_time <>", value, "retryTime");
			return (Criteria) this;
		}

		public Criteria andRetryTimeGreaterThan(Integer value) {
			addCriterion("retry_time >", value, "retryTime");
			return (Criteria) this;
		}

		public Criteria andRetryTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("retry_time >=", value, "retryTime");
			return (Criteria) this;
		}

		public Criteria andRetryTimeLessThan(Integer value) {
			addCriterion("retry_time <", value, "retryTime");
			return (Criteria) this;
		}

		public Criteria andRetryTimeLessThanOrEqualTo(Integer value) {
			addCriterion("retry_time <=", value, "retryTime");
			return (Criteria) this;
		}

		public Criteria andRetryTimeIn(List<Integer> values) {
			addCriterion("retry_time in", values, "retryTime");
			return (Criteria) this;
		}

		public Criteria andRetryTimeNotIn(List<Integer> values) {
			addCriterion("retry_time not in", values, "retryTime");
			return (Criteria) this;
		}

		public Criteria andRetryTimeBetween(Integer value1, Integer value2) {
			addCriterion("retry_time between", value1, value2, "retryTime");
			return (Criteria) this;
		}

		public Criteria andRetryTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("retry_time not between", value1, value2, "retryTime");
			return (Criteria) this;
		}

		public Criteria andSleepTimeIsNull() {
			addCriterion("sleep_time is null");
			return (Criteria) this;
		}

		public Criteria andSleepTimeIsNotNull() {
			addCriterion("sleep_time is not null");
			return (Criteria) this;
		}

		public Criteria andSleepTimeEqualTo(Integer value) {
			addCriterion("sleep_time =", value, "sleepTime");
			return (Criteria) this;
		}

		public Criteria andSleepTimeNotEqualTo(Integer value) {
			addCriterion("sleep_time <>", value, "sleepTime");
			return (Criteria) this;
		}

		public Criteria andSleepTimeGreaterThan(Integer value) {
			addCriterion("sleep_time >", value, "sleepTime");
			return (Criteria) this;
		}

		public Criteria andSleepTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("sleep_time >=", value, "sleepTime");
			return (Criteria) this;
		}

		public Criteria andSleepTimeLessThan(Integer value) {
			addCriterion("sleep_time <", value, "sleepTime");
			return (Criteria) this;
		}

		public Criteria andSleepTimeLessThanOrEqualTo(Integer value) {
			addCriterion("sleep_time <=", value, "sleepTime");
			return (Criteria) this;
		}

		public Criteria andSleepTimeIn(List<Integer> values) {
			addCriterion("sleep_time in", values, "sleepTime");
			return (Criteria) this;
		}

		public Criteria andSleepTimeNotIn(List<Integer> values) {
			addCriterion("sleep_time not in", values, "sleepTime");
			return (Criteria) this;
		}

		public Criteria andSleepTimeBetween(Integer value1, Integer value2) {
			addCriterion("sleep_time between", value1, value2, "sleepTime");
			return (Criteria) this;
		}

		public Criteria andSleepTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("sleep_time not between", value1, value2, "sleepTime");
			return (Criteria) this;
		}

		public Criteria andTimeOutIsNull() {
			addCriterion("time_out is null");
			return (Criteria) this;
		}

		public Criteria andTimeOutIsNotNull() {
			addCriterion("time_out is not null");
			return (Criteria) this;
		}

		public Criteria andTimeOutEqualTo(Integer value) {
			addCriterion("time_out =", value, "timeOut");
			return (Criteria) this;
		}

		public Criteria andTimeOutNotEqualTo(Integer value) {
			addCriterion("time_out <>", value, "timeOut");
			return (Criteria) this;
		}

		public Criteria andTimeOutGreaterThan(Integer value) {
			addCriterion("time_out >", value, "timeOut");
			return (Criteria) this;
		}

		public Criteria andTimeOutGreaterThanOrEqualTo(Integer value) {
			addCriterion("time_out >=", value, "timeOut");
			return (Criteria) this;
		}

		public Criteria andTimeOutLessThan(Integer value) {
			addCriterion("time_out <", value, "timeOut");
			return (Criteria) this;
		}

		public Criteria andTimeOutLessThanOrEqualTo(Integer value) {
			addCriterion("time_out <=", value, "timeOut");
			return (Criteria) this;
		}

		public Criteria andTimeOutIn(List<Integer> values) {
			addCriterion("time_out in", values, "timeOut");
			return (Criteria) this;
		}

		public Criteria andTimeOutNotIn(List<Integer> values) {
			addCriterion("time_out not in", values, "timeOut");
			return (Criteria) this;
		}

		public Criteria andTimeOutBetween(Integer value1, Integer value2) {
			addCriterion("time_out between", value1, value2, "timeOut");
			return (Criteria) this;
		}

		public Criteria andTimeOutNotBetween(Integer value1, Integer value2) {
			addCriterion("time_out not between", value1, value2, "timeOut");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table site
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table site
     *
     * @mbggenerated do_not_delete_during_merge Thu Feb 09 10:07:49 GMT+08:00 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}