package com.unbank.mybatis.entity;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_id
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_name
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_pwd
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private String userPwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_permission
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private String userPermission;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_email
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private String userEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_phone
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private String userPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_reg_time
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private Date userRegTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.ssoid
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private String ssoid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.last_login_ip
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private String lastLoginIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.validata_code
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private String validataCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.outDate
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private Date outdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.last_login_time
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private Date lastLoginTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.user_id
	 * @return  the value of user.user_id
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.user_id
	 * @param userId  the value for user.user_id
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.user_name
	 * @return  the value of user.user_name
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.user_name
	 * @param userName  the value for user.user_name
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.user_pwd
	 * @return  the value of user.user_pwd
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public String getUserPwd() {
		return userPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.user_pwd
	 * @param userPwd  the value for user.user_pwd
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.user_permission
	 * @return  the value of user.user_permission
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public String getUserPermission() {
		return userPermission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.user_permission
	 * @param userPermission  the value for user.user_permission
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setUserPermission(String userPermission) {
		this.userPermission = userPermission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.user_email
	 * @return  the value of user.user_email
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public String getUserEmail() {
		return userEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.user_email
	 * @param userEmail  the value for user.user_email
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.user_phone
	 * @return  the value of user.user_phone
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public String getUserPhone() {
		return userPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.user_phone
	 * @param userPhone  the value for user.user_phone
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.user_reg_time
	 * @return  the value of user.user_reg_time
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public Date getUserRegTime() {
		return userRegTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.user_reg_time
	 * @param userRegTime  the value for user.user_reg_time
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setUserRegTime(Date userRegTime) {
		this.userRegTime = userRegTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.ssoid
	 * @return  the value of user.ssoid
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public String getSsoid() {
		return ssoid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.ssoid
	 * @param ssoid  the value for user.ssoid
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setSsoid(String ssoid) {
		this.ssoid = ssoid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.last_login_ip
	 * @return  the value of user.last_login_ip
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public String getLastLoginIp() {
		return lastLoginIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.last_login_ip
	 * @param lastLoginIp  the value for user.last_login_ip
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setLastLoginIp(String lastLoginIp) {
		this.lastLoginIp = lastLoginIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.validata_code
	 * @return  the value of user.validata_code
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public String getValidataCode() {
		return validataCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.validata_code
	 * @param validataCode  the value for user.validata_code
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setValidataCode(String validataCode) {
		this.validataCode = validataCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.outDate
	 * @return  the value of user.outDate
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public Date getOutdate() {
		return outdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.outDate
	 * @param outdate  the value for user.outDate
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setOutdate(Date outdate) {
		this.outdate = outdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.last_login_time
	 * @return  the value of user.last_login_time
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public Date getLastLoginTime() {
		return lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.last_login_time
	 * @param lastLoginTime  the value for user.last_login_time
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}
}