package com.unbank.mybatis.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public UserExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Integer value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Integer value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Integer value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Integer value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Integer> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Integer> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Integer value1, Integer value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNull() {
			addCriterion("user_name is null");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNotNull() {
			addCriterion("user_name is not null");
			return (Criteria) this;
		}

		public Criteria andUserNameEqualTo(String value) {
			addCriterion("user_name =", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotEqualTo(String value) {
			addCriterion("user_name <>", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThan(String value) {
			addCriterion("user_name >", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("user_name >=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThan(String value) {
			addCriterion("user_name <", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThanOrEqualTo(String value) {
			addCriterion("user_name <=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLike(String value) {
			addCriterion("user_name like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotLike(String value) {
			addCriterion("user_name not like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameIn(List<String> values) {
			addCriterion("user_name in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotIn(List<String> values) {
			addCriterion("user_name not in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameBetween(String value1, String value2) {
			addCriterion("user_name between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotBetween(String value1, String value2) {
			addCriterion("user_name not between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andUserPwdIsNull() {
			addCriterion("user_pwd is null");
			return (Criteria) this;
		}

		public Criteria andUserPwdIsNotNull() {
			addCriterion("user_pwd is not null");
			return (Criteria) this;
		}

		public Criteria andUserPwdEqualTo(String value) {
			addCriterion("user_pwd =", value, "userPwd");
			return (Criteria) this;
		}

		public Criteria andUserPwdNotEqualTo(String value) {
			addCriterion("user_pwd <>", value, "userPwd");
			return (Criteria) this;
		}

		public Criteria andUserPwdGreaterThan(String value) {
			addCriterion("user_pwd >", value, "userPwd");
			return (Criteria) this;
		}

		public Criteria andUserPwdGreaterThanOrEqualTo(String value) {
			addCriterion("user_pwd >=", value, "userPwd");
			return (Criteria) this;
		}

		public Criteria andUserPwdLessThan(String value) {
			addCriterion("user_pwd <", value, "userPwd");
			return (Criteria) this;
		}

		public Criteria andUserPwdLessThanOrEqualTo(String value) {
			addCriterion("user_pwd <=", value, "userPwd");
			return (Criteria) this;
		}

		public Criteria andUserPwdLike(String value) {
			addCriterion("user_pwd like", value, "userPwd");
			return (Criteria) this;
		}

		public Criteria andUserPwdNotLike(String value) {
			addCriterion("user_pwd not like", value, "userPwd");
			return (Criteria) this;
		}

		public Criteria andUserPwdIn(List<String> values) {
			addCriterion("user_pwd in", values, "userPwd");
			return (Criteria) this;
		}

		public Criteria andUserPwdNotIn(List<String> values) {
			addCriterion("user_pwd not in", values, "userPwd");
			return (Criteria) this;
		}

		public Criteria andUserPwdBetween(String value1, String value2) {
			addCriterion("user_pwd between", value1, value2, "userPwd");
			return (Criteria) this;
		}

		public Criteria andUserPwdNotBetween(String value1, String value2) {
			addCriterion("user_pwd not between", value1, value2, "userPwd");
			return (Criteria) this;
		}

		public Criteria andUserPermissionIsNull() {
			addCriterion("user_permission is null");
			return (Criteria) this;
		}

		public Criteria andUserPermissionIsNotNull() {
			addCriterion("user_permission is not null");
			return (Criteria) this;
		}

		public Criteria andUserPermissionEqualTo(String value) {
			addCriterion("user_permission =", value, "userPermission");
			return (Criteria) this;
		}

		public Criteria andUserPermissionNotEqualTo(String value) {
			addCriterion("user_permission <>", value, "userPermission");
			return (Criteria) this;
		}

		public Criteria andUserPermissionGreaterThan(String value) {
			addCriterion("user_permission >", value, "userPermission");
			return (Criteria) this;
		}

		public Criteria andUserPermissionGreaterThanOrEqualTo(String value) {
			addCriterion("user_permission >=", value, "userPermission");
			return (Criteria) this;
		}

		public Criteria andUserPermissionLessThan(String value) {
			addCriterion("user_permission <", value, "userPermission");
			return (Criteria) this;
		}

		public Criteria andUserPermissionLessThanOrEqualTo(String value) {
			addCriterion("user_permission <=", value, "userPermission");
			return (Criteria) this;
		}

		public Criteria andUserPermissionLike(String value) {
			addCriterion("user_permission like", value, "userPermission");
			return (Criteria) this;
		}

		public Criteria andUserPermissionNotLike(String value) {
			addCriterion("user_permission not like", value, "userPermission");
			return (Criteria) this;
		}

		public Criteria andUserPermissionIn(List<String> values) {
			addCriterion("user_permission in", values, "userPermission");
			return (Criteria) this;
		}

		public Criteria andUserPermissionNotIn(List<String> values) {
			addCriterion("user_permission not in", values, "userPermission");
			return (Criteria) this;
		}

		public Criteria andUserPermissionBetween(String value1, String value2) {
			addCriterion("user_permission between", value1, value2, "userPermission");
			return (Criteria) this;
		}

		public Criteria andUserPermissionNotBetween(String value1, String value2) {
			addCriterion("user_permission not between", value1, value2, "userPermission");
			return (Criteria) this;
		}

		public Criteria andUserEmailIsNull() {
			addCriterion("user_email is null");
			return (Criteria) this;
		}

		public Criteria andUserEmailIsNotNull() {
			addCriterion("user_email is not null");
			return (Criteria) this;
		}

		public Criteria andUserEmailEqualTo(String value) {
			addCriterion("user_email =", value, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailNotEqualTo(String value) {
			addCriterion("user_email <>", value, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailGreaterThan(String value) {
			addCriterion("user_email >", value, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailGreaterThanOrEqualTo(String value) {
			addCriterion("user_email >=", value, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailLessThan(String value) {
			addCriterion("user_email <", value, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailLessThanOrEqualTo(String value) {
			addCriterion("user_email <=", value, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailLike(String value) {
			addCriterion("user_email like", value, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailNotLike(String value) {
			addCriterion("user_email not like", value, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailIn(List<String> values) {
			addCriterion("user_email in", values, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailNotIn(List<String> values) {
			addCriterion("user_email not in", values, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailBetween(String value1, String value2) {
			addCriterion("user_email between", value1, value2, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailNotBetween(String value1, String value2) {
			addCriterion("user_email not between", value1, value2, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserPhoneIsNull() {
			addCriterion("user_phone is null");
			return (Criteria) this;
		}

		public Criteria andUserPhoneIsNotNull() {
			addCriterion("user_phone is not null");
			return (Criteria) this;
		}

		public Criteria andUserPhoneEqualTo(String value) {
			addCriterion("user_phone =", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneNotEqualTo(String value) {
			addCriterion("user_phone <>", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneGreaterThan(String value) {
			addCriterion("user_phone >", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("user_phone >=", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneLessThan(String value) {
			addCriterion("user_phone <", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneLessThanOrEqualTo(String value) {
			addCriterion("user_phone <=", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneLike(String value) {
			addCriterion("user_phone like", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneNotLike(String value) {
			addCriterion("user_phone not like", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneIn(List<String> values) {
			addCriterion("user_phone in", values, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneNotIn(List<String> values) {
			addCriterion("user_phone not in", values, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneBetween(String value1, String value2) {
			addCriterion("user_phone between", value1, value2, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneNotBetween(String value1, String value2) {
			addCriterion("user_phone not between", value1, value2, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserRegTimeIsNull() {
			addCriterion("user_reg_time is null");
			return (Criteria) this;
		}

		public Criteria andUserRegTimeIsNotNull() {
			addCriterion("user_reg_time is not null");
			return (Criteria) this;
		}

		public Criteria andUserRegTimeEqualTo(Date value) {
			addCriterion("user_reg_time =", value, "userRegTime");
			return (Criteria) this;
		}

		public Criteria andUserRegTimeNotEqualTo(Date value) {
			addCriterion("user_reg_time <>", value, "userRegTime");
			return (Criteria) this;
		}

		public Criteria andUserRegTimeGreaterThan(Date value) {
			addCriterion("user_reg_time >", value, "userRegTime");
			return (Criteria) this;
		}

		public Criteria andUserRegTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("user_reg_time >=", value, "userRegTime");
			return (Criteria) this;
		}

		public Criteria andUserRegTimeLessThan(Date value) {
			addCriterion("user_reg_time <", value, "userRegTime");
			return (Criteria) this;
		}

		public Criteria andUserRegTimeLessThanOrEqualTo(Date value) {
			addCriterion("user_reg_time <=", value, "userRegTime");
			return (Criteria) this;
		}

		public Criteria andUserRegTimeIn(List<Date> values) {
			addCriterion("user_reg_time in", values, "userRegTime");
			return (Criteria) this;
		}

		public Criteria andUserRegTimeNotIn(List<Date> values) {
			addCriterion("user_reg_time not in", values, "userRegTime");
			return (Criteria) this;
		}

		public Criteria andUserRegTimeBetween(Date value1, Date value2) {
			addCriterion("user_reg_time between", value1, value2, "userRegTime");
			return (Criteria) this;
		}

		public Criteria andUserRegTimeNotBetween(Date value1, Date value2) {
			addCriterion("user_reg_time not between", value1, value2, "userRegTime");
			return (Criteria) this;
		}

		public Criteria andSsoidIsNull() {
			addCriterion("ssoid is null");
			return (Criteria) this;
		}

		public Criteria andSsoidIsNotNull() {
			addCriterion("ssoid is not null");
			return (Criteria) this;
		}

		public Criteria andSsoidEqualTo(String value) {
			addCriterion("ssoid =", value, "ssoid");
			return (Criteria) this;
		}

		public Criteria andSsoidNotEqualTo(String value) {
			addCriterion("ssoid <>", value, "ssoid");
			return (Criteria) this;
		}

		public Criteria andSsoidGreaterThan(String value) {
			addCriterion("ssoid >", value, "ssoid");
			return (Criteria) this;
		}

		public Criteria andSsoidGreaterThanOrEqualTo(String value) {
			addCriterion("ssoid >=", value, "ssoid");
			return (Criteria) this;
		}

		public Criteria andSsoidLessThan(String value) {
			addCriterion("ssoid <", value, "ssoid");
			return (Criteria) this;
		}

		public Criteria andSsoidLessThanOrEqualTo(String value) {
			addCriterion("ssoid <=", value, "ssoid");
			return (Criteria) this;
		}

		public Criteria andSsoidLike(String value) {
			addCriterion("ssoid like", value, "ssoid");
			return (Criteria) this;
		}

		public Criteria andSsoidNotLike(String value) {
			addCriterion("ssoid not like", value, "ssoid");
			return (Criteria) this;
		}

		public Criteria andSsoidIn(List<String> values) {
			addCriterion("ssoid in", values, "ssoid");
			return (Criteria) this;
		}

		public Criteria andSsoidNotIn(List<String> values) {
			addCriterion("ssoid not in", values, "ssoid");
			return (Criteria) this;
		}

		public Criteria andSsoidBetween(String value1, String value2) {
			addCriterion("ssoid between", value1, value2, "ssoid");
			return (Criteria) this;
		}

		public Criteria andSsoidNotBetween(String value1, String value2) {
			addCriterion("ssoid not between", value1, value2, "ssoid");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpIsNull() {
			addCriterion("last_login_ip is null");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpIsNotNull() {
			addCriterion("last_login_ip is not null");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpEqualTo(String value) {
			addCriterion("last_login_ip =", value, "lastLoginIp");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpNotEqualTo(String value) {
			addCriterion("last_login_ip <>", value, "lastLoginIp");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpGreaterThan(String value) {
			addCriterion("last_login_ip >", value, "lastLoginIp");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpGreaterThanOrEqualTo(String value) {
			addCriterion("last_login_ip >=", value, "lastLoginIp");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpLessThan(String value) {
			addCriterion("last_login_ip <", value, "lastLoginIp");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpLessThanOrEqualTo(String value) {
			addCriterion("last_login_ip <=", value, "lastLoginIp");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpLike(String value) {
			addCriterion("last_login_ip like", value, "lastLoginIp");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpNotLike(String value) {
			addCriterion("last_login_ip not like", value, "lastLoginIp");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpIn(List<String> values) {
			addCriterion("last_login_ip in", values, "lastLoginIp");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpNotIn(List<String> values) {
			addCriterion("last_login_ip not in", values, "lastLoginIp");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpBetween(String value1, String value2) {
			addCriterion("last_login_ip between", value1, value2, "lastLoginIp");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpNotBetween(String value1, String value2) {
			addCriterion("last_login_ip not between", value1, value2, "lastLoginIp");
			return (Criteria) this;
		}

		public Criteria andValidataCodeIsNull() {
			addCriterion("validata_code is null");
			return (Criteria) this;
		}

		public Criteria andValidataCodeIsNotNull() {
			addCriterion("validata_code is not null");
			return (Criteria) this;
		}

		public Criteria andValidataCodeEqualTo(String value) {
			addCriterion("validata_code =", value, "validataCode");
			return (Criteria) this;
		}

		public Criteria andValidataCodeNotEqualTo(String value) {
			addCriterion("validata_code <>", value, "validataCode");
			return (Criteria) this;
		}

		public Criteria andValidataCodeGreaterThan(String value) {
			addCriterion("validata_code >", value, "validataCode");
			return (Criteria) this;
		}

		public Criteria andValidataCodeGreaterThanOrEqualTo(String value) {
			addCriterion("validata_code >=", value, "validataCode");
			return (Criteria) this;
		}

		public Criteria andValidataCodeLessThan(String value) {
			addCriterion("validata_code <", value, "validataCode");
			return (Criteria) this;
		}

		public Criteria andValidataCodeLessThanOrEqualTo(String value) {
			addCriterion("validata_code <=", value, "validataCode");
			return (Criteria) this;
		}

		public Criteria andValidataCodeLike(String value) {
			addCriterion("validata_code like", value, "validataCode");
			return (Criteria) this;
		}

		public Criteria andValidataCodeNotLike(String value) {
			addCriterion("validata_code not like", value, "validataCode");
			return (Criteria) this;
		}

		public Criteria andValidataCodeIn(List<String> values) {
			addCriterion("validata_code in", values, "validataCode");
			return (Criteria) this;
		}

		public Criteria andValidataCodeNotIn(List<String> values) {
			addCriterion("validata_code not in", values, "validataCode");
			return (Criteria) this;
		}

		public Criteria andValidataCodeBetween(String value1, String value2) {
			addCriterion("validata_code between", value1, value2, "validataCode");
			return (Criteria) this;
		}

		public Criteria andValidataCodeNotBetween(String value1, String value2) {
			addCriterion("validata_code not between", value1, value2, "validataCode");
			return (Criteria) this;
		}

		public Criteria andOutdateIsNull() {
			addCriterion("outDate is null");
			return (Criteria) this;
		}

		public Criteria andOutdateIsNotNull() {
			addCriterion("outDate is not null");
			return (Criteria) this;
		}

		public Criteria andOutdateEqualTo(Date value) {
			addCriterion("outDate =", value, "outdate");
			return (Criteria) this;
		}

		public Criteria andOutdateNotEqualTo(Date value) {
			addCriterion("outDate <>", value, "outdate");
			return (Criteria) this;
		}

		public Criteria andOutdateGreaterThan(Date value) {
			addCriterion("outDate >", value, "outdate");
			return (Criteria) this;
		}

		public Criteria andOutdateGreaterThanOrEqualTo(Date value) {
			addCriterion("outDate >=", value, "outdate");
			return (Criteria) this;
		}

		public Criteria andOutdateLessThan(Date value) {
			addCriterion("outDate <", value, "outdate");
			return (Criteria) this;
		}

		public Criteria andOutdateLessThanOrEqualTo(Date value) {
			addCriterion("outDate <=", value, "outdate");
			return (Criteria) this;
		}

		public Criteria andOutdateIn(List<Date> values) {
			addCriterion("outDate in", values, "outdate");
			return (Criteria) this;
		}

		public Criteria andOutdateNotIn(List<Date> values) {
			addCriterion("outDate not in", values, "outdate");
			return (Criteria) this;
		}

		public Criteria andOutdateBetween(Date value1, Date value2) {
			addCriterion("outDate between", value1, value2, "outdate");
			return (Criteria) this;
		}

		public Criteria andOutdateNotBetween(Date value1, Date value2) {
			addCriterion("outDate not between", value1, value2, "outdate");
			return (Criteria) this;
		}

		public Criteria andLastLoginTimeIsNull() {
			addCriterion("last_login_time is null");
			return (Criteria) this;
		}

		public Criteria andLastLoginTimeIsNotNull() {
			addCriterion("last_login_time is not null");
			return (Criteria) this;
		}

		public Criteria andLastLoginTimeEqualTo(Date value) {
			addCriterion("last_login_time =", value, "lastLoginTime");
			return (Criteria) this;
		}

		public Criteria andLastLoginTimeNotEqualTo(Date value) {
			addCriterion("last_login_time <>", value, "lastLoginTime");
			return (Criteria) this;
		}

		public Criteria andLastLoginTimeGreaterThan(Date value) {
			addCriterion("last_login_time >", value, "lastLoginTime");
			return (Criteria) this;
		}

		public Criteria andLastLoginTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("last_login_time >=", value, "lastLoginTime");
			return (Criteria) this;
		}

		public Criteria andLastLoginTimeLessThan(Date value) {
			addCriterion("last_login_time <", value, "lastLoginTime");
			return (Criteria) this;
		}

		public Criteria andLastLoginTimeLessThanOrEqualTo(Date value) {
			addCriterion("last_login_time <=", value, "lastLoginTime");
			return (Criteria) this;
		}

		public Criteria andLastLoginTimeIn(List<Date> values) {
			addCriterion("last_login_time in", values, "lastLoginTime");
			return (Criteria) this;
		}

		public Criteria andLastLoginTimeNotIn(List<Date> values) {
			addCriterion("last_login_time not in", values, "lastLoginTime");
			return (Criteria) this;
		}

		public Criteria andLastLoginTimeBetween(Date value1, Date value2) {
			addCriterion("last_login_time between", value1, value2, "lastLoginTime");
			return (Criteria) this;
		}

		public Criteria andLastLoginTimeNotBetween(Date value1, Date value2) {
			addCriterion("last_login_time not between", value1, value2, "lastLoginTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated do_not_delete_during_merge Thu Feb 09 10:07:50 GMT+08:00 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}