package com.unbank.mybatis.entity;

public class UserSite {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_site.id
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_site.user_id
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_site.site_id
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private Integer siteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_site.del
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	private Integer del;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_site.id
	 * @return  the value of user_site.id
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_site.id
	 * @param id  the value for user_site.id
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_site.user_id
	 * @return  the value of user_site.user_id
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_site.user_id
	 * @param userId  the value for user_site.user_id
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_site.site_id
	 * @return  the value of user_site.site_id
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public Integer getSiteId() {
		return siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_site.site_id
	 * @param siteId  the value for user_site.site_id
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setSiteId(Integer siteId) {
		this.siteId = siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_site.del
	 * @return  the value of user_site.del
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public Integer getDel() {
		return del;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_site.del
	 * @param del  the value for user_site.del
	 * @mbggenerated  Thu Feb 16 14:30:04 GMT+08:00 2017
	 */
	public void setDel(Integer del) {
		this.del = del;
	}
}